var newCacheName = 'pouchdb-assets-cache-v2018-04-09 14:01:37 +0000';

var criticalAssets = [
  '/offline.html',
  'assets/styles/style.min.css',
];

var pages = [
    '/404.html',
    '/offline.html',
    '/index.html',
    '/dining.html',
    '/shopping.html',
    '/health.html',
    '/tours.html',
    '/map.html',
    '/fids.html',

    '/dining_bars_bistros.html',
    '/dining_bars_bistros_anchor_inn.html',
    '/dining_bars_bistros_brewery.html',
    '/dining_bars_bistros_cafe_vila.html',
    '/dining_bars_bistros_francesca.html',
    '/dining_bars_bistros_lava_lounge.html',
    '/dining_bars_bistros_mooring.html',
    '/dining_bars_bistros_ramada.html',
    '/dining_bars_bistros_secretgarden.html',
    '/dining_bars_bistros_stonegrill.html',
    '/dining_bars_bistros_the_beach.html',
    '/dining_bars_bistros_the_lookout.html',
    '/dining_bars_bistros_the_office_pub.html',
    '/dining_bars_bistros_wahoo.html',
    '/dining_bars_bistros_war_horse.html',
    '/dining_bars_bistros_waterfront.html',
    '/dining_cafes.html',
    '/dining_cafes_au_peche_mignon.html',
    '/dining_cafes_jills.html',
    '/dining_cafes_jungle.html',
    '/dining_cafes_nambawan.html',
    '/dining_cafes_rossi.html',
    '/dining_chinese.html',
    '/dining_chinese_au_tong.html',
    '/dining_chinese_crystal_palace,.html',
    '/dining_chinese_harbour_view.html',
    '/dining_curry_house_spice_indian.html',
    '/dining_curry_house_sydney.html',
    '/dining_curryhouse.html',
    '/dining_finedining_resortdining.html',
    '/dining_finedining_resortdining_benjor.html',
    '/dining_finedining_resortdining_blue_marlin.html',
    '/dining_finedining_resortdining_breakas.html',
    '/dining_finedining_resortdining_cafe_du_village.html',
    '/dining_finedining_resortdining_cafe_vila.html',
    '/dining_finedining_resortdining_chill.html',
    '/dining_finedining_resortdining_coconut_palms.html',
    '/dining_finedining_resortdining_erakor.html',
    '/dining_finedining_resortdining_eratap.html',
    '/dining_finedining_resortdining_francesca.html',
    '/dining_finedining_resortdining_grand.html',
    '/dining_finedining_resortdining_hideaway.html',
    '/dining_finedining_resortdining_holiday_inn.html',
    '/dining_finedining_resortdining_iririki.html',
    '/dining_finedining_resortdining_lagoon_tropicana.html',
    '/dining_finedining_resortdining_le_life.html',
    '/dining_finedining_resortdining_melanesian.html',
    '/dining_finedining_resortdining_paradise_cove.html',
    '/dining_finedining_resortdining_ramada.html',
    '/dining_finedining_resortdining_reefers.html',
    '/dining_finedining_resortdining_seaside_retreat.html',
    '/dining_finedining_resortdining_sunset.html',
    '/dining_finedining_resortdining_tillys_chantillys.html',
    '/dining_finedining_resortdining_vila_chaumieres.html',
    '/dining_finedining_resortdining_wild_ginger.html',
    '/dining_fish_chips.html',
    '/dining_fish_chips_beach_hut.html',
    '/dining_french.html',
    '/dining_french_au_fare.html',
    '/dining_french_lehoustalet.html',
    '/dining_japanese.html',
    '/dining_japanese_kanpai.html',
    '/dining_japanese_rorona.html',
    '/dining_japanese_shiro.html',
    '/dining_philipino.html',
    '/dining_philipino_kuciana.html',
    '/dining_steak_house.html',
    '/dining_steak_house_beef_house.html',
    '/dining_steak_house_flaming_bull.html',
    '/dining_takeway.html',
    '/dining_takeway_crave_food.html',
    '/dining_takeway_emilys.html',
    '/dining_takeway_island_time.html',
    '/dining_takeway_sea_view.html',
    '/dining_thai.html',
    '/dining_thai_ka_exotic.html',
    '/dining_thai_pad_thai.html',
    '/dining_thai_thailand_massage.html',
    '/dining_vietnamese.html',
    '/dining_vietnamese_joe.html',

    '/fids_domestic.html',
    '/fids_international.html',

    '/health_body_fitness_gym.html',
    '/health_body_fitness_gym_fit_for_life.html',
    '/health_body_fitness_gym_musclelab.html',
    '/health_body_fitness_gym_power_house.html',
    '/health_body_fitness_gym_ultimate_fitness.html',
    '/health_body_fitness_gym_vanuatu_yoga.html',
    '/health_hair_dresser_beauty_salon.html',
    '/health_hair_dresser_beauty_salon_body_soul.html',
    '/health_hair_dresser_beauty_salon_clipper_city.html',
    '/health_hair_dresser_beauty_salon_eden_hair.html',
    '/health_hair_dresser_beauty_salon_head_hunter.html',
    '/health_spa_massage.html',
    '/health_spa_massage_ahn.html',
    '/health_spa_massage_king.html',
    '/health_spa_massage_kool.html',
    '/health_spa_massage_lotus_day.html',
    '/health_spa_massage_nature_beauty.html',
    '/health_spa_massage_paradise.html',
    '/health_spa_massage_vanuatu_spa.html',
    '/health_spa_massage_volcanic_earth.html',
    '/health_tattoo_shop.html',
    '/health_tattoo_shop_oki_dokie.html',

    '/map_adventure_quad_tours.html',
    '/map_brewery_bar.html',
    '/map_cafe_du_village.html',
    '/map_clipper_city.html',
    '/map_epicure.html',
    '/map_jungle.html',
    '/map_lehoustalet.html',
    '/map_nambawan.html',
    '/map_off_road_adventure.html',
    '/map_oki_dokie.html',
    '/map_pandanus.html',
    '/map_prouds.html',
    '/map_ramada.html',
    '/map_reef_explorer.html',
    '/map_secretgarden.html',
    '/map_vanuatu_helicopters.html',
    '/map_war_horse.html',

    '/shopping_boutique.html',
    '/shopping_boutique_billabong.html',
    '/shopping_boutique_elysium.html',
    '/shopping_boutique_etam.html',
    '/shopping_boutique_pandanus.html',
    '/shopping_boutique_rococo.html',
    '/shopping_boutique_roxy.html',
    '/shopping_boutique_splash.html',
    '/shopping_boutique_tropicool.html',
    '/shopping_duty_free.html',
    '/shopping_duty_free_fung_kuei.html',
    '/shopping_duty_free_paris_shopping.html',
    '/shopping_duty_free_prouds.html',
    '/shopping_duty_free_sound_center.html',
    '/shopping_liquor_shop.html',
    '/shopping_liquor_shop_dockside.html',
    '/shopping_liquor_shop_epicure.html',
    '/shopping_liquor_shop_vanuatu_wine.html',
    '/shopping_liquor_shop_vila_bottle.html',
    '/shopping_market.html',
    '/shopping_market_gs_cellars.html',
    '/shopping_market_hebdrida.html',
    '/shopping_market_mamas.html',
    '/shopping_market_vanuatu_handicaft.html',
    '/shopping_phamarcy.html',
    '/shopping_phamarcy_drug_store.html',
    '/shopping_phamarcy_healtwise.html',
    '/shopping_phamarcy_tana_plaza.html',
    '/shopping_supermarkets.html',
    '/shopping_supermarkets_au_bon_mache.html',
    '/shopping_supermarkets_cash_carry.html',
    '/shopping_supermarkets_cello_vila.html',
    '/shopping_supermarkets_traverso.html',

    '/tours_buggy_tours.html',
    '/tours_buggy_tours_off_road_adventure.html',
    '/tours_culture_tours.html',
    '/tours_culture_tours_balihai.html',
    '/tours_culture_tours_ekasup.html',
    '/tours_culture_tours_secretgarden.html',
    '/tours_cycling.html',
    '/tours_cycling_eco.html',
    '/tours_cycling_jungle_moutain.html',
    '/tours_day_cruise.html',
    '/tours_day_cruise_coongoola.html',
    '/tours_day_cruise_okeanos.html',
    '/tours_day_cruise_sailaway.html',
    '/tours_day_cruise_turtle_reef.html',
    '/tours_eco_tours.html',
    '/tours_eco_tours_dream.html',
    '/tours_eco_tours_eco.html',
    '/tours_eco_tours_evergreen.html',
    '/tours_eco_tours_melanesian.html',
    '/tours_fishing.html',
    '/tours_fishing_crusoe.html',
    '/tours_fishing_island.html',
    '/tours_fishing_lelepa.html',
    '/tours_fishing_sport.html',
    '/tours_glass_bottom_boat.html',
    '/tours_glass_bottom_boat_reef_explorer.html',
    '/tours_glass_bottom_boat_turtle_reef.html',
    '/tours_helicopter_tours.html',
    '/tours_helicopter_tours_vanuatu_helicopters.html',
    '/tours_horse_riding.html',
    '/tours_horse_riding_bellevue.html',
    '/tours_horse_riding_club_hippique.html',
    '/tours_island_day_tours.html',
    '/tours_island_day_tours_atmosphere.html',
    '/tours_island_day_tours_dream_tours.html',
    '/tours_island_day_tours_melanesian.html',
    '/tours_island_day_tours_native_round.html',
    '/tours_jet_boat.html',
    '/tours_jet_boat_tropic_thunder.html',
    '/tours_jet_ski.html',
    '/tours_jet_ski_joes.html',
    '/tours_kayaking.html',
    '/tours_kayaking_eco.html',
    '/tours_kayaking_kayaking.html',
    '/tours_kayaking_le_life.html',
    '/tours_parasailing.html',
    '/tours_parasailing_pv_parasailing.html',
    '/tours_quad_tours.html',
    '/tours_quad_tours_adventure_quad_tours.html',
    '/tours_scuba_diving.html',
    '/tours_scuba_diving_big_blue.html',
    '/tours_scuba_diving_hideaway.html',
    '/tours_scuba_diving_nautilus.html',
    '/tours_scuba_diving_tranquillity.html',
    '/tours_snorkelling.html',
    '/tours_snorkelling_big_blue.html',
    '/tours_snorkelling_hideaway.html',
    '/tours_snorkelling_le_life.html',
    '/tours_snorkelling_reef_explorer.html',
    '/tours_snorkelling_tranquillity.html',
    '/tours_snorkelling_turtle_reef.html',
    '/tours_underwater_post_office.html',
    '/tours_underwater_post_office_hideaway.html',
    '/tours_underwater_tours.html',
    '/tours_underwater_tours_oceanwalker.html',
    '/tours_underwater_tours_sea_doo.html',
    '/tours_volcano_flight_tours.html',
    '/tours_volcano_flight_tours_air_safaris.html',
    '/tours_volcano_flight_tours_unity_airlines.html',
    '/tours_volcano_flight_tours_vanuatu_helicopters.html',
    '/tours_walking.html',
    '/tours_walking_eco.html',
    '/tours_walking_le_life.html',
    '/tours_waterfall_tours.html',
    '/tours_waterfall_tours_eco.html',
    '/tours_waterfall_tours_evergreen.html',
    '/tours_waterfall_tours_le_life.html',
    '/tours_waterfall_tours_melanesian.html',
    '/tours_waterfall_tours_mele_cascade.html',
    '/tours_waterfall_tours_rarru_rantapau.html',
    '/tours_zego.html',
    '/tours_zego_u_power.html',
    '/tours_zipline.html',
    '/tours_zipline_zipline.html',
    '/tours_zorb_ride.html',
    '/tours_zorb_ride_wet_wild.html',
    '/',
];

self.addEventListener('activate', function(event) {
  // remove caches beginning "pouchdb-" that aren't the new cache
  event.waitUntil(
    caches.keys()
      .then(function(cacheNames) {
        return Promise.all(
          cacheNames.map(function(cacheName) {
            if (!/^pouchdb-/.test(cacheName)) {
              return;
            }
            if (newCacheName !== cacheName) {
              return caches.delete(cacheName);
            }
          })
        );
      })
      .then(function() {
        return self.clients.claim();
      })
  );
});

self.addEventListener('fetch', function(event) {
  // Try the cache, if it's not in there try the network, then cache that response
  // if that network request fails show the offline.html page.
  event.respondWith(
    caches.open(newCacheName).then(function(cache) {
      return cache.match(event.request).then(function (response) {
        return response || fetch(event.request).then(function(response) {
          cache.put(event.request, response.clone());
          return response;
        }).catch(function () {
          return cache.match('/offline.html',);
        });
      });
   })
  );
});
